# how pycache work


print("welcome to the first project of python")

def service(a):
    print(f"get a best service {a}")

print("need more service")

# hello.cpython-313.pyc
# this file is generated by python interpreter
# it is a bytecode file that contains the compiled version of the python code
# it is stored in the __pycache__ directory
# it is used to speed up the execution of the python code
# it is automatically generated by the python interpreter when the python code is executed
# it is used to store the compiled version of the python code
# the name 312 means that it is compiled for python version 3.12

# 